trigger:
  paths:
    include:
    - result/*
resources:
  repositories:
  - repository: self
variables:
- name: dockerRegistryServiceConnection
  value: 'd2f9c5c5-85db-4706-8a26-e5e16d7660f4'
- name: imageRepository
  value: 'resultapp'
- name: containerRegistry
  value: 'voteappacr2.azurecr.io'
- name: dockerfilePath
  value: '$(Build.SourcesDirectory)/vote/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
pool:
  name: 'votingapp-gents'
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'voteappACR2'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'result/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName: Push
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push image to ACR
      inputs:
        containerRegistry: 'voteappACR2'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'

