trigger:
  paths:
    include:
    - vote/*
resources:
  repositories:
  - repository: self
variables:
- name: dockerRegistryServiceConnection
  value: 'f200819a-9184-4546-a50f-ffa454764809'
- name: imageRepository
  value: 'votingapp'
- name: containerRegistry
  value: 'voteappacr2.azurecr.io'
- name: dockerfilePath
  value: '$(Build.SourcesDirectory)/vote/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
pool:
  name: 'votingapp-gents'
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'voteappACR2'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName: Push
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push image to ACR
      inputs:
        containerRegistry: 'voteappACR2'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'

